#!/usr/bin/env python

import argparse
import os
import sys
import textwrap
import yaml

from odoosync.ModelSyncer import ModelSyncer, SyncException


def helptext(host):
    message = textwrap.dedent(
        f"""
        Authentication for host '{host}' failed.

        Add credentials to a netrc file, for example:

            machine {host}
              login <your-username>
              password <your-password>

        You can store the file in ~/.netrc or supply a custom location with
        the --netrc-file flag.
        """
    ).strip()
    print(message)
    sys.exit(1)


def build_parser():
    description = textwrap.dedent(
        """
        Synchronise records between two Odoo instances using a declarative YAML
        configuration. Each run records timestamps so that subsequent runs only
        transmit changes by default.
        """
    )
    epilog = textwrap.dedent(
        """
        Examples:
          odoosync projects.yaml
          odoosync projects.yaml --netrc-file ~/.config/odoosync/credentials.netrc
          odoosync projects.yaml --sync-dependencies
          odoosync projects.yaml --force-sync --sync-dependencies
        """
    )
    parser = argparse.ArgumentParser(
        description=description,
        epilog=epilog,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        'yamlfile',
        metavar='CONFIG',
        help='Path to the YAML configuration describing the sync job',
    )
    parser.add_argument(
        '--netrc-file',
        dest='netrc_file',
        help='Override the netrc path used for authentication lookup',
    )
    parser.add_argument(
        '--sync-dependencies',
        action='store_true',
        help='Also create related records discovered via many2one dependencies',
    )
    parser.add_argument(
        '--force-sync',
        action='store_true',
        help='Ignore timestamps and sync all records regardless of last update',
    )
    return parser


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    yamlfile = args.yamlfile
    _struct = {}

    with open(yamlfile, 'r') as _file:
        _struct = yaml.load(_file, Loader=yaml.SafeLoader)

    if args.netrc_file or args.sync_dependencies or args.force_sync:
        options = _struct.setdefault('options', {})
        if args.netrc_file:
            options['netrc_path'] = args.netrc_file
        if args.sync_dependencies:
            options['sync_dependencies'] = True
        if args.force_sync:
            options['force_sync'] = True

    # Open timestamp file
    timestampfile = os.path.splitext(yamlfile)[0] + '.timestamp'
    _timestamps = {}
    try:
        with open(timestampfile, 'r') as _file:
            _timestamps = yaml.load(_file, Loader=yaml.SafeLoader)
    except IOError:
        pass

    # Sync
    try:
        instance = ModelSyncer(_struct, _timestamps)
    except SyncException as e:
        helptext(e.args[0])
    instance.prepare()
    instance.sync()
    _timestamps = instance.get_new_timestamps()
    if _timestamps:
        with open(timestampfile, 'w') as _file:
            yaml.dump(_timestamps, _file)


if __name__ == "__main__":
    main()

